### ISSUE TITLE
Can we query to get raw value of enum ?

### ISSUE THREAD

**Issue by lufutu** [kenn/enum_accessor#9]
Hi there,
Has any solution to get raw value of enums instead string value when query collection of active record objects ? I know we can get raw value by _raw each object but how to get this `raw` value when select ?
Thanks

**Comment by kenn** [comment]
What is your use case like? The values are stored and retrieved as integer until AR accessor casts them as string so it shouldn't be hard, but I want to understand what you're trying to do.

**Comment by lufutu** [comment]
The problem is enum value cast to string but we have an API endpoint and I want return number instead string from API. Front-end displays enum as string is okay but with API I want it's return integer, not a string value.

**Comment by kenn** [comment]
So you mean when you build the JSON? Then it should be easy whatever library you use to build it.

With `active_model_serializers` for instance, you can do something like:

``` ruby
def gender
  object.gender_raw
end
```

or

``` ruby
[:gender, :kind].each do |attr|
  define_method attr do
    object.send("#{attr}_raw")
  end
end
```

if you want to generate methods in bulk.

**Comment by lufutu** [comment]
Thank you so much!
